### ISSUE TITLE
Wina options not available outside of the location folder

### ISSUE THREAD

**Issue by whazzabii** [albertvanderhorst/ciforth#11]
I don't know if I have overlooked something, but I am not able to use the starting options for wina, except my working directory is the folder where all of the wina files are.

I downloaded the prebuild release of wina64-5.5.0 and unpacked it. I actually have a .tools folder in my path; so I installed wina64 like descriped in the READMEwina.txt with wina64 -i ~\.tools\wina64.exe ~\.tools\forth.lab %COMSPEC%.
When I run wina from any other folder then wina's home  directory, I get an error code 8:
tools\wina64.exe" -n ? ciforth ERROR # 8        // as full error message

Is this normal behavior? Is there a solution to fix this and use every option everwhere?
I don't want to have to jump to wina home directory and use an absolue path to a file I want to compile.

Thanks for any help!

**Comment by albertvanderhorst** [comment]
I'm not familiar with the ~ character in Microsoft filenames. 
You can debug this situation by starting up wina. 
`BLOCK-FILE $@ TYPE` 
should reveal the forth.lab configured. 
`BLOCK-FILE $@ GET-FILE TYPE` 
should print the library file.
The path where you install forth.lab should be an absolute path.  Probably it is wise to also explicitly add the drive like so

> C:\USERS\PROGRAMS_..\BLA..\BLA..\tools\forth.lab.

**Comment by whazzabii** [comment]
Thanks for the response!

I didn't used the ~ char for installation, because the .tools folder lies directly in C: (C:\.tools), in most cases Windows should not accept the ~ as Linux systems do. 

I tried the `BLOCK-FILE` commands, the first one printed out forth.lab but the second one gave me  ? ciforth ERROR # -2.

In the meantime I also installed ciforth on my Ubuntu WSL, but I get the same errors and also only can use the starting options when inside of the home directory of lina.

I don't know what further informations I could give to reproduce my error. I litteraly just downloaded, unpacked and run the install command.

**Comment by albertvanderhorst** [comment]
You have discovered a defect. The -i option doesn't work, because the library file is supposed to be burned into the executable, but it no longer is.  A work around is to copy forth.lab to you current work directory. I This triggers a 5.5.1 release.

**Comment by albertvanderhorst** [comment]
The release 5.5.0 is replace by 5.5.1 for all 4 user install archives. See release 5.5
